[alembic]
script_location = alembic
sqlalchemy.url = postgresql+psycopg://postgres:postgres@db:5432/quiz_db

[post_write_hooks]
hooks = {}

[logger_alembic]
level = INFO
handlers = console
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
